#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=10:00:00
#PBS -l vmem=8gb
#PBS -N specularityAnalysis
#PBS -e specError.txt
#PBS -o specLog.txt
#### For getting emails: PBS -M yourName@email.com #for receiving emails when certain tasks are complete (specified by PBS -m option): #PBS -m be #emails when the job is aborted(a),begins execution(b), is terminate(e)
#PBS -M dkwong@iu.edu
#PBS -m ae
cd $PBS_O_WORKDIR
echo "Current working directory is `pwd`"
echo $PBS_JOBNAME
echo "Starting run at: `date`"
python specAnalysis.py
echo "Program diffuse finished with exit code $? at: `date`"
