#!/bin/bash
#### EDIT THIS FILE FOR RAMSEYFRINGE.PY ####

#PBS -l nodes=1:ppn=1,walltime=10:00:00
#PBS -l vmem=2gb
#PBS -N PENTrack
#PBS -e /N/u/dkwong/Carbonate/PENTrack/out/error.txt
#PBS -o /N/dc2/scratch/dkwong/output_JOB_NUM.txt
#### For getting emails: PBS -M yourName@email.com #for receiving emails when certain tasks are complete (specified by PBS -m option): #PBS -m be #emails when the job is aborted(a),begins execution(b), is terminate(e)
###PBS -M dkwong@iu.edu
###PBS -m a
cd $PBS_O_WORKDIR
echo "Current working directory is `pwd`"
echo $PBS_JOBNAME
echo "Starting run at: `date`"
./PENTrack JOB_NUM "CONFIG_FILE" "./out"
#also put log files .o / .e in a subfolder in same output folder
echo "Program diffuse finished with exit code $? at: `date`"
