# Analyzes output generated by ppm ramp
from __future__ import print_function
import numpy as np
import argparse
import pandas as pd
import sys
import os

import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

def main():
    ###### arguments #######
    folder = '/N/dc2/scratch/dkwong/'
    # folder = '/mnt/c/Users/Doug/Downloads'
    joblist = 'joblist.out'
    # joblist = '/mnt/c/Users/Doug/Downloads/joblist.out'
    query = 'xend > 0.99'   # For no query, write 'all'
    E_HIST_ON = True        # Plots E start histogram for each B field
    T_HIST_ON = True        # Plots t end histogram for each B field
    nbins = 250
    histRange = [0,500E-9]  # neV
    timeRange = [0,50]      # seconds
    ########################

    if query != "all":
        print('Applying filter to neutrons:')
        print(query)

    print('Reading ', joblist)
    startRun, endRun, param = np.genfromtxt(joblist, unpack=True, comments='#')

    # Scale to 6 Telsa ramp
    param = np.array(param) * 6
    neutronCount = []
    Estart = []
    tend = []
    binEdges =[]

    if (folder[-1] != '/'):
        folder = folder + '/'

    for start, end, p in zip(startRun, endRun, param):
        print('\nReading run files where B ~ ',p, ' [T]')
        runNum = np.arange(int(start),int(end)+1)
        total = 0
        totalBeforeQuery = 0
        histTotal = np.zeros(nbins)
        timeTotal = np.zeros( int(timeRange[1]-timeRange[0]) )
        missedRuns = []

        for i in runNum:
            runName = folder + str(i).zfill(12) + 'neutronend.out'
            print(i,'...', end='')
            sys.stdout.flush()      # Yes, I know print has a flush=True option. Doesn't work in python2
            try:
                df = pd.read_csv(runName, delim_whitespace=True)# usecols=[1,6,7,8,9,10,11,12,14,18,19,20,21,26,27,28,30,32,33,34])
                # Queries may involve any property listed below:
                # ['particle', 'vxstart', 'vystart', 'vzstart','polstart', 'Sxstart', 'Systart', 'Szstart', 'Estart', 'tend',
                # 'xend', 'yend', 'zend', 'Sxend', 'Syend', 'Szend','Eend', 'BxEnd', 'ByEnd', 'BzEnd']

                totalBeforeQuery += len(df.index)
                if query != "all":
                    df = df.query(query)
            except:
                missedRuns.append(i)
                continue

            total += len(df.index)
            histTemp, binEdges = np.histogram(df['Estart'],range = histRange, bins = nbins)
            histTotal += histTemp

            # Time histogram
            timeTemp, timeEdges = np.histogram(df['tend'], range = timeRange, bins=int(timeRange[1]-timeRange[0]) )
            timeTotal += timeTemp
        #ENDFOR

        print('okay!')
        print('Total neutrons simulated: ', totalBeforeQuery)
        print('Neutrons after query: ', total)
        print('Neutrons in hist: ', np.sum(histTotal))
        print('Error reading run numbers-- ', missedRuns)
        neutronCount.append( float(total)/float(totalBeforeQuery) )
        Estart.append(histTotal)
        tend.append(timeTotal)
    #ENDFOR

    print('\nPlotting...',end='')
    plt.figure()
    plt.plot(param, np.divide(neutronCount,neutronCount[0]) ,marker='.')
    plt.xlabel('B [T]')
    plt.ylabel('Neutron count')
    plt.title('PPM ramp')
    plt.grid()
    plt.savefig('PPM_ramp.png')
    plt.close()

    for p, E, t in zip(param, Estart, tend):
        if E_HIST_ON:
            fig, ax = plt.subplots()
            ax.bar(binEdges[1:], E, width=(histRange[1]-histRange[0])/float(nbins))
            ax.set_xlabel('E [neV]')
            ax.set_xlim([histRange[0] , histRange[1]])
            ax.set_ylabel('Number of neutrons')
            plt.savefig('Estart_B=' + str(np.round(p, decimals=3)) + '.png')
            plt.close()
        if T_HIST_ON:
            fig, ax = plt.subplots()
            ax.bar(timeEdges[1:], t, width=(timeRange[1]-timeRange[0])/float(int(timeRange[1]-timeRange[0])))
            ax.set_xlabel('time [sec]')
            ax.set_xlim([timeRange[0] , timeRange[1]])
            ax.set_ylabel('Number of neutrons')
            plt.savefig('t_B=' + str(np.round(p, decimals=3)) + '.png')
            plt.close()

    print('Done!')



    return

if ( __name__ == '__main__' ):
    main()
